# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
# add the Firebase pod for Google Analytics
pod 'Firebase/Core', :modular_headers => true
pod 'Firebase/Analytics', :modular_headers => true
pod 'Firebase/DynamicLinks', :modular_headers => true
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

target 'bitrequest' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
use_modular_headers!
end