# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
# add the Firebase pod for Google Analytics
pod 'Firebase/Core'
pod 'Firebase/Analytics'
pod 'Firebase/DynamicLinks'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

target 'bitrequest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
end